sudo: required

- uses: deblockt/cucumber-report-annotations-action@v1.7
  with:
    access-token: ${{ secrets.GITHUB_TOKEN }}
    path: "**/cucumber-report.json"

language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "at-12"
    token: ${SONAR_TOKEN}

script:
  - ./gradlew check
  - sonar-scanner
  - ./gradlew executeBDDTests -PclientId=$CLIENTID  -PclientSecret=$CLIENTSECRET -Pusername=$USERNAME -Ppassword=$PASSWORD
